export async function getAllUsers() {
  return [
    {
      id: 1,
      name: "John Admin",
      email: "john@company.com",
      companyName: "Tech Corp",
      role: "admin",
    },
    {
      id: 2,
      name: "Jass",
      email: "jass@company.com",
      companyName: "Tech Corp",
      role: "user",
    },
    {
      id: 3,
      name: "Sandeep",
      email: "Sandeep@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep1",
      email: "Sandeep1@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep2",
      email: "Sandeep2@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep3",
      email: "Sandeep3@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep4",
      email: "Sandeep4@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep5",
      email: "Sandeep5@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep6",
      email: "Sandeep6@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep7",
      email: "Sandeep7@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep8",
      email: "Sandeep8@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep9",
      email: "Sandeep9@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep10",
      email: "Sandeep10@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep11",
      email: "Sandeep11@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep12",
      email: "Sandeep12@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep13",
      email: "Sandeep13@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep14",
      email: "Sandeep14@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep15",
      email: "Sandeep15@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
    {
      id: 3,
      name: "Sandeep16",
      email: "Sandeep16@company.com",
      companyName: "Tech Corp",
      role: "guest",
    },
  ];
}

export async function updateUserRole(id: number, role: string) {
  return { success: true };
}
